In [13]:

# Identfy the file location of the master dataset
I_data_path = './csv/CCStr.csv' 

# Define file name of output .csv file
I_out_filename = 'clean_master_Densidad'

I_data_densidad = './csv/Densidad_poblacion/'

#Load libraries
import pandas as pd
import numpy as np
import warnings
from datetime import datetime
warnings.filterwarnings('ignore') 
pd.options.display.max_columns = None
pd.options.display.max_rows = None



# Define inputs
Master_path = I_data_path     
o_fname = I_out_filename;


## Load data:
data = pd.read_csv(Master_path)
del data['Unnamed: 0']  
print(data.shape)
## Provincias
provincias_list = ['Almería', 'Cádiz', 'Córdoba', 'Granada', 'Huelva', 'Jaén', 'Málaga', 'Sevilla']

## Cargando datos 
provincias_list_csv = []
Provincias_df = pd.DataFrame()
for i in provincias_list:
    df = pd.read_excel(I_data_densidad + i + '.xlsx', sheet_name='tabla-9687')
    df['Key_merge'] = df['Fecha']+i
    Provincias_df = Provincias_df.append(df, ignore_index = True)


# Densidad: 0-4 años
Provincias_df['Densidad: 0-4 años']=Provincias_df.iloc[:, 2] 
for i in range(3, 7):    
    Provincias_df['Densidad: 0-4 años']+=Provincias_df.iloc[:, i] 

# Densidad: 5-18 años
Provincias_df['Densidad: 5-18 años']=Provincias_df.iloc[:, 7] 
for i in range(8, 21):    
    Provincias_df['Densidad: 5-18 años']+=Provincias_df.iloc[:, i] 

# Densidad: 19-30 años
Provincias_df['Densidad: 19-30 años']=Provincias_df.iloc[:, 21] 
for i in range(22, 33):    
    Provincias_df['Densidad: 19-30 años']+=Provincias_df.iloc[:, i] 

# Densidad: 31-45 años
Provincias_df['Densidad: 31-45 años']=Provincias_df.iloc[:, 33] 
for i in range(34, 48):    
    Provincias_df['Densidad: 31-45 años']+=Provincias_df.iloc[:, i] 

# Densidad: 46-65 años
Provincias_df['Densidad: 46-65 años']=Provincias_df.iloc[:, 48] 
for i in range(49, 68):    
    Provincias_df['Densidad: 46-65 años']+=Provincias_df.iloc[:, i] 

# Densidad: 66-75 años
Provincias_df['Densidad: 66-75 años']=Provincias_df.iloc[:, 68] 
for i in range(69, 78):    
    Provincias_df['Densidad: 66-75 años']+=Provincias_df.iloc[:, i] 

# Densidad: 76> años
Provincias_df['Densidad: 76> años']=Provincias_df.iloc[:, 78] 
for i in range(79, 103):    
    Provincias_df['Densidad: 76> años']+=Provincias_df.iloc[:, i] 

# Creamos la key:
l_fecha = []
for i in range(len(data)):
    if data['Mes'][i]<7:
        l_fecha.append('1 de enero de ' + str(data['Año'][i])+data['DESC_PROVINCIA'][i])
    elif data['Mes'][i]>6:
        l_fecha.append('1 de julio de ' + str(data['Año'][i])+data['DESC_PROVINCIA'][i])
data['Key_merge'] = l_fecha

## Merge
col_merge = ['Key_merge', 'Densidad: 0-4 años', 'Densidad: 5-18 años', 'Densidad: 19-30 años', 'Densidad: 31-45 años', 
             'Densidad: 46-65 años', 'Densidad: 66-75 años', 'Densidad: 76> años']


data = pd.merge(data, Provincias_df[col_merge], left_on= 'Key_merge', right_on= 'Key_merge', how='left')

(67688, 15)

In [14]:
data.head()

,ARTICULO,CENTROCONSUMO,DESC_PROVINCIA,Año,Mes,CANTIDADSALIDA,Horas_Sol,Precipitacion,Temp_Max,Temp_Min,Presion_Max,Presion_Min,Viento_Max,Viento_Min,CENTROCONSUMO_str,Key_merge,Densidad: 0-4 años,Densidad: 5-18 años,Densidad: 19-30 años,Densidad: 31-45 años,Densidad: 46-65 años,Densidad: 66-75 años,Densidad: 76> años
0,-1073438649,17405,Córdoba,2008,1,8.0,171.5,70.0,16.93871,5.119355,1016.954839,1011.587097,23.469677,5.098065,174,1 de enero de 2008Córdoba,42073,123677,134617,185557,178212,66689,61856
1,-1073438649,17407,Córdoba,2008,1,40.0,171.5,70.0,16.93871,5.119355,1016.954839,1011.587097,23.469677,5.098065,174,1 de enero de 2008Córdoba,42073,123677,134617,185557,178212,66689,61856
2,-1073438649,17409,Córdoba,2008,1,40.0,171.5,70.0,16.93871,5.119355,1016.954839,1011.587097,23.469677,5.098065,174,1 de enero de 2008Córdoba,42073,123677,134617,185557,178212,66689,61856
3,-1073438649,17414,Córdoba,2008,1,293.0,171.5,70.0,16.93871,5.119355,1016.954839,1011.587097,23.469677,5.098065,174,1 de enero de 2008Córdoba,42073,123677,134617,185557,178212,66689,61856
4,-1073438649,17415,Córdoba,2008,1,59.0,171.5,70.0,16.93871,5.119355,1016.954839,1011.587097,23.469677,5.098065,174,1 de enero de 2008Córdoba,42073,123677,134617,185557,178212,66689,61856

In [12]:
Provincias_df.head()

,Fecha,Total,0 años,1 año,2 años,3 años,4 años,5 años,6 años,7 años,8 años,9 años,10 años,11 años,12 años,13 años,14 años,15 años,16 años,17 años,18 años,19 años,20 años,21 años,22 años,23 años,24 años,25 años,26 años,27 años,28 años,29 años,30 años,31 años,32 años,33 años,34 años,35 años,36 años,37 años,38 años,39 años,40 años,41 años,42 años,43 años,44 años,45 años,46 años,47 años,48 años,49 años,50 años,51 años,52 años,53 años,54 años,55 años,56 años,57 años,58 años,59 años,60 años,61 años,62 años,63 años,64 años,65 años,66 años,67 años,68 años,69 años,70 años,71 años,72 años,73 años,74 años,75 años,76 años,77 años,78 años,79 años,80 años,81 años,82 años,83 años,84 años,85 años,86 años,87 años,88 años,89 años,90 años,91 años,92 años,93 años,94 años,95 años,96 años,97 años,98 años,99 años,100 y más años,Key_merge,Densidad: 0-4 años,Densidad: 5-18 años,Densidad: 19-30 años,Densidad: 31-45 años,Densidad: 46-65 años,Densidad: 66-75 años,Densidad: 76> años
0,1 de julio de 2017,700704,7601,7958,8042,7981,7967,8142,8264,8332,8716,8690,8432,8340,8044,7799,7472,7408,7478,7494,7453,7379,7425,7517,7604,7789,8228,8404,8629,8849,8993,9296,9396,9501,9726,10077,10685,11267,11684,12049,12225,12360,12583,12526,12086,11692,11519,11370,11070,10902,10835,10780,10623,10351,10264,10027,9481,9104,9059,8950,8692,8412,7771,7277,7025,6780,6725,6546,6223,6054,6228,6143,5738,5455,5100,4791,4390,3837,4065,3661,3042,3428,3550,3419,3192,2917,2662,2403,2135,1840,1562,1331,1088,900,696,508,386,278,191,123,78,67,80,1 de julio de 2017Almería,39549,112064,99509,171350,180674,53959,43602
1,1 de enero de 2017,700041,7826,7997,8031,7871,8034,8243,8281,8402,9057,8324,8553,8148,7934,7645,7277,7517,7397,7524,7289,7376,7396,7538,7533,7905,8442,8313,8897,8738,9195,9348,9417,9583,9935,10300,11121,11460,11980,12218,12335,12479,12771,12400,11904,11543,11546,11282,10964,10954,10803,10832,10484,10301,10323,9809,9210,9015,9124,8793,8618,8262,7309,7275,6810,6779,6696,6437,6074,6119,6452,5973,5618,5421,4938,4769,4136,3676,4613,2875,3367,3675,3626,3418,3176,2880,2682,2380,2152,1747,1601,1298,1075,893,643,506,394,253,182,101,82,75,71,1 de enero de 2017Almería,39759,111591,100098,172857,178798,53176,43765
2,1 de julio de 2016,698033,7692,7986,7942,7957,8145,8282,8363,8744,8693,8438,8355,8051,7785,7447,7390,7439,7430,7382,7295,7350,7441,7482,7647,8121,8341,8582,8798,8937,9261,9385,9512,9771,10142,10741,11317,11759,12137,12313,12459,12656,12612,12202,11765,11575,11442,11150,10985,10910,10851,10682,10412,10337,10094,9531,9125,9093,8990,8724,8441,7781,7303,7046,6789,6760,6578,6255,6113,6296,6229,5816,5553,5220,4886,4499,3958,4194,3791,3166,3574,3715,3595,3365,3099,2877,2630,2361,2037,1750,1520,1261,1067,837,631,499,359,246,165,106,90,59,69,1 de julio de 2016Almería,39722,111094,100857,174041,176687,52764,42869
3,1 de enero de 2016,696186,7935,7955,7857,8035,8272,8293,8429,9076,8320,8545,8147,7957,7618,7275,7479,7375,7481,7259,7297,7351,7467,7444,7764,8364,8244,8852,8658,9130,9355,9422,9590,9912,10331,11146,11431,11954,12283,12413,12588,12802,12456,11990,11608,11595,11327,10988,11003,10853,10870,10533,10343,10368,9843,9258,9023,9134,8817,8641,8305,7312,7313,6784,6781,6755,6401,6131,6153,6480,6014,5670,5534,5017,4859,4243,3760,4731,2970,3471,3807,3775,3591,3342,3062,2893,2574,2367,1916,1770,1457,1249,1062,770,621,477,324,243,135,106,97,41,71,1 de enero de 2016Almería,40054,110551,101641,174824,174468,52461,42191
4,1 de julio de 2015,693634,7624,7881,7947,8150,8272,8354,8758,8711,8447,8354,8059,7792,7439,7364,7416,7426,7358,7250,7303,7383,7429,7567,8008,8260,8513,8726,8861,9200,9347,9477,9743,10127,10759,11317,11711,12123,12353,12515,12690,12606,12227,11814,11613,11467,11155,11000,10947,10892,10728,10453,10354,10094,9543,9138,9079,8979,8742,8483,7811,7319,7053,6785,6787,6606,6285,6154,6342,6283,5870,5632,5307,4977,4601,4039,4281,3893,3266,3688,3851,3763,3546,3279,3064,2820,2562,2243,1936,1698,1443,1248,989,751,611,449,310,212,137,114,83,51,164,1 de julio de 2015Almería,39874,110031,102514,175477,172232,51225,42278